parameters:
  AgentPool : 'Linux-CPU'
  JobName : 'Linux_CI_Dev'
  BuildCommand: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -x "--use_mklml --use_tvm --build_wheel"'
  DoNugetPack: 'false'
  NuPackScript: ''
  ArtifactName: 'drop-linux'

jobs:
- job: ${{ parameters.JobName }}
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
      submodules: true
    - template: linux-set-variables-and-download.yml
    - script: ${{ parameters.BuildCommand }}
      displayName: 'Command Line Script'
    - ${{ if eq(parameters['DoNugetPack'], 'true') }}:
      - script: |
         ${{ parameters.NuPackScript }}
        displayName: 'Create Artifacts'
      - task: PublishPipelineArtifact@0
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: ${{ parameters.ArtifactName }}
          targetPath: '$(Build.ArtifactStagingDirectory)'
