jobs:
- job: Linux_CI_Dev
  timeoutInMinutes: 0
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
    - script: 'git submodule update --init --recursive'
    - template: templates/set-test-data-variables-step.yml

    - script: 'tools/ci_build/github/linux/run_dockerbuild.sh -o android -r $(Build.BinariesDirectory) -d nnapi -x " --android --android_ndk_path /android-ndk/ --android_abi x86_64 --use_dnnlibrary"'
      displayName: 'Command Line Script'

    # - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    #   displayName: 'Component Detection'
    #   condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    #
    # - template: templates/clean-agent-build-directory-step.yml

