jobs:
- job: Android_CI
  pool: 
    vmImage: 'macOS-10.14'
  steps:
    # cmake 3.15 breaks Android NDK https://gitlab.kitware.com/cmake/cmake/issues/19515. pip install cmake==3.13.2 installs 3.12.2
    - script: pip install cmake==3.13.2.post1 && alias cmake=/usr/local/bin/cmake && cmake --version && brew install coreutils gnu-sed
      displayName: Install cmake 3.14 and coreutils
    - script: 'git submodule update --init --recursive --progress'
      displayName: Clone submodules
    - script: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'ndk-bundle'
      displayName: Install Android NDK
    - script: gsed -i 's/-g$//' $ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
    - script: cat $ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake | grep "\-g"
    - script: tools/ci_build/build.py --android --build_dir build --android_ndk $ANDROID_HOME/ndk-bundle --android_abi=x86_64 --skip_submodule_sync --parallel --use_dnnlibrary --update --build
      displayName: Build and Test on Android Emulator
    - task: CopyFiles@2
      inputs:
        sourceFolder: 'build'
        contents: '**/onnx_test_runner'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop
